export class UserSession{
    userId:string;
    dayId:number;
    organizationId:string;
    platformPartner:string;
    insertTimestamp:any;
    updateTimestamp:any;
    userCmdId:string;
    firstName:string;
    middleName:string;
    lastName:string;
    organizationName:string;
    organizationCmdId:string;
    districtId:string;
    districtCmdId:string;
    districtName:string;
    subDistrictId:string;
    subDistrictCmdId:string;
    subDistrictName:string;
    stateCode:string;
    countryCode:string;
    platformId:string;
    userRole:string;
    date:{
        startDate:number,
        endDate:number
    };
    // yet to conform type
    extensions:string;
    eventCreatedBy:string;
    eventCreatedDate:any;
    eventIds:[{
        eventId:String,
        timeStamp:any
    }];
    eventLastUpdatedBy:string;
    eventLastUpdatedDate:any;
    classes:[{
        classId:string,
        classCmdId:string
    }];
    role:string;
    action:[{
        loginHour:number,
        loginTimeStamp:any,
        sessionTimeSpent:number,
        exitedTimeStamp:any
    }];
    result:{
        userLoginCount:number,
        userLoginCountHour:[number],
        userTotalTimeSpent:number
    };
}